# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "49ffda534d37caee5cf88b0b4cb3de1e"
name = "form-collector"
handle = "form-collector"
application_url = "https://prior-entries-deals-indicator.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://prior-entries-deals-indicator.trycloudflare.com/auth/callback",
  "https://prior-entries-deals-indicator.trycloudflare.com/auth/shopify/callback",
  "https://prior-entries-deals-indicator.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
